version: '3.6'
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app-tier
    healthcheck:
      test: [ "CMD", "/opt/bitnami/zookeeper/bin/zkServer.sh", "/opt/bitnami/zookeeper/conf/zoo.cfg", "status" ]
      interval: 30s
      timeout: 5s
      retries: 2
      start_period: 10s
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
    networks:
      - app-tier
    depends_on:
      - zookeeper
  mongodb:
    image: 'mongo:4-xenial'
    ports:
      - '27017:27017'

networks:
  app-tier:
    driver: bridge
